In [1]:
import pandas as pd

In [2]:
#read the csv file
df=pd.read_csv("sample_data/players_20.csv")

#set short_name to the index of our dataframe
df=df.set_index("short_name")

#select columns
df=df[["long_name", "age", "dob", "height_cm", "weight_kg", "nationality", "club"]]

In [3]:
#show df
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

**1 Sample()**

In [14]:
#extract 10 random elements from the "nationality" column
df['nationality'].sample(10, random_state=99)   # we get 10 random players from the dataframe

#the random_state() method controls the number of times the data generates random data

short_name
R. Alvarado               Mexico
Qiao Wei                China PR
E. Paredes                 Chile
K. Stoyanov             Bulgaria
M. Chudý                Slovakia
D. Sundaram                India
R. Gagliardini             Italy
G. Debeljuh              Croatia
Kim Seung Yong    Korea Republic
M. Hansen                Denmark
Name: nationality, dtype: object

In [19]:
#extract a random 20% sample of dataframe
df.sample(frac=0.2, random_state=10)      #frac stands for fraction and this provides 20% oft the data

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
F. Ortega,Francisco Ortega,20,1999-03-19,177,75,Argentina,Vélez Sarsfield
M. Ilaimaharitra,Marco Ilaimaharitra,23,1995-07-26,177,79,Madagascar,Sporting de Charleroi
D. Parker,Devante Parker,23,1996-03-16,175,66,Germany,1. FSV Mainz 05
H. Mendoza,Humberto Antonio Mendoza Quiñónez,34,1984-10-02,189,85,Colombia,Envigado FC
K. Qaka,Kamer Qaka,24,1995-04-11,170,73,Albania,Universitatea Craiova
...,...,...,...,...,...,...,...
A. Koșelev,Alexei Koșelev,25,1993-11-19,200,90,Moldova,Fortuna Sittard
P. Ejimadu,Phillip Ejimadu,19,1999-08-31,188,98,United States,Los Angeles FC
E. List,Elliott List,22,1997-05-12,174,74,England,Gillingham
V. Bondarenko,Valeriy Bondarenko,25,1994-02-03,194,88,Ukraine,Vitória Guimarães
T. Chunchukov,Tsvetelin Chunchukov,24,1994-12-26,181,75,Bulgaria,Bulgaria

In [25]:
#Upsampling: increase the sample rate, specify the frac>1
df.sample(frac=2, replace=True, random_state=23)    #double the rows of the original dataframe

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
B. Enobakhare,Bright Enobakhare,21,1998-05-18,179,77,Nigeria,Wigan Athletic
Vitor Costa,Vitor Costa de Brito,25,1994-07-01,182,73,Brazil,Racing Club de Lens
Song Bum Keun,송범근 Bum Keun Song,21,1997-10-15,194,88,Korea Republic,Jeonbuk Hyundai Motors
J. Willis,Joe Willis,30,1988-08-10,196,84,United States,Houston Dynamo
L. Jans,Laurent Jans,26,1992-08-05,178,76,Luxembourg,SC Paderborn 07
...,...,...,...,...,...,...,...
M. Kelly,Michael Kelly,22,1996-07-13,196,86,Republic of Ireland,Bohemian FC
H. Reed,Harrison Reed,24,1995-01-27,176,72,England,Fulham
T. King,Tom King,24,1995-03-09,192,80,England,Newport County
P. Costea,Paul Costea,20,1999-03-02,173,63,Romania,Gaz Metan Mediaş
S. Gigot,Samuel Gigot,25,1993-10-12,187,83,France,Spartak Moscow