In [3]:
import pandas as pd

In [4]:
#read the csv file
df=pd.read_csv("sample_data/players_20.csv")
df

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18273,245006,https://sofifa.com/player/245006/shuai-shao/20...,Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
18274,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
18275,252332,https://sofifa.com/player/252332/wei-zhang/20/...,Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
18276,251110,https://sofifa.com/player/251110/haijian-wang/...,Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
18277,233449,https://sofifa.com/player/233449/ximing-pan/20...,Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [5]:
#set short_name to the index of our dataframe
df=df.set_index("short_name")

In [6]:
#show the dataframe
df

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shao Shuai,245006,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
Xiao Mingjie,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
Zhang Wei,252332,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
Wang Haijian,251110,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
Pan Ximing,233449,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [7]:
df.head(1)

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2

In [8]:
#select columns
df=df[["long_name", "age", "dob", "height_cm", "weight_kg", "nationality", "club"]]

In [9]:
#show the df
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

**1 Selecting with a single Value**

loc[row_label, column_label]

In [10]:
#get all data about L.messi
df.loc["L. Messi"]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [11]:
#get the height of L.Messi
df.loc["L. Messi", "height_cm"]

np.int64(170)

In [12]:
#get infor on Cr7
df.loc["Cristiano Ronaldo"]

long_name      Cristiano Ronaldo dos Santos Aveiro
age                                             34
dob                                     1985-02-05
height_cm                                      187
weight_kg                                       83
nationality                               Portugal
club                                      Juventus
Name: Cristiano Ronaldo, dtype: object

In [13]:
#get weight of CR7
df.loc["Cristiano Ronaldo", "weight_kg"]

np.int64(83)

In [14]:
#get all rows inside the height_cm
df.loc[:,'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [15]:
#select all coluns that correspong to the index 'L.Messi'
df.loc['L. Messi',:]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

**2. Selecting with a list of values**

In [20]:
#get all data about L.Messi and cristiano
df.loc[["L. Messi", "Cristiano Ronaldo"]]   #we add the elements(index) in our list

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [21]:
#get the height of L.Messi and Cristiano Ronaldo
df.loc[["L. Messi", "Cristiano Ronaldo"], "height_cm"]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [24]:
#get the height, weight of L.Messi
df.loc["L. Messi", ["height_cm", "weight_kg"]]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [25]:
#get height anc weight of L.Messi and Cristiano Ronaldo
df.loc[["L. Messi", "Cristiano Ronaldo"], ["height_cm", "weight_kg"]]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

**3 Selecting a range of data with a slice**

start:stop:stop
start and stop elements are included

In [27]:
#slice column labels
players=["L. Messi", "Cristiano Ronaldo"]

#our slice goes from 'age':'club'
df.loc[players, 'age':'club']

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [34]:
#slice index labels
columns=['age','dob', 'height_cm','weight_kg', 'nationality']

#get top1 and top10 player name
df.index[:10]   #the first 10 players

df.loc['L. Messi':'M. Salah', columns]

                   age         dob  height_cm  weight_kg  nationality
short_name
L. Messi            32  1987-06-24        170         72    Argentina
Cristiano Ronaldo   34  1985-02-05        187         83     Portugal
Neymar Jr           27  1992-02-05        175         68       Brazil
J. Oblak            26  1993-01-07        188         87     Slovenia
E. Hazard           28  1991-01-07        175         74      Belgium
K. De Bruyne        28  1991-06-28        181         70      Belgium
M. ter Stegen       27  1992-04-30        187         85      Germany
V. van Dijk         27  1991-07-08        193         92  Netherlands
L. Modrić           33  1985-09-09        172         66      Croatia
M. Salah            27  1992-06-15        175         71        Egypt

**4 Selecting with conditions**

In [31]:
#one condition: select player with height above 180cm
columns=['age','dob', 'height_cm','weight_kg']

#we add condition and then the columns we want
df.loc[df['height_cm']> 180, columns]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [35]:
#Multiple conditions: select player with height above 180cm from Argentina
(df['nationality']=="Argentina") & (df['height_cm']> 180)

df.loc[(df['nationality']=="Argentina") & (df['height_cm']> 180), columns]

                age         dob  height_cm  weight_kg nationality
short_name
M. Icardi        26  1993-02-19        181         75   Argentina
G. Higuaín       31  1987-12-10        186         89   Argentina
E. Garay         32  1986-10-10        189         90   Argentina
N. Otamendi      31  1988-02-12        183         81   Argentina
G. Rulli         27  1992-05-20        189         84   Argentina
...             ...         ...        ...        ...         ...
T. Durso         20  1999-02-26        185         80   Argentina
J. Hass          21  1998-03-27        186         88   Argentina
R. Ferrario      19  2000-04-30        186         76   Argentina
L. Finochietto   22  1997-04-25        186         77   Argentina
N. Forastiero    20  1998-07-16        182         79   Argentina

[350 rows x 5 columns]

In [37]:
#display clubs we have
df.value_counts('club')

club
AS Monaco                     33
1. FC Union Berlin            33
1. FSV Mainz 05               33
Aston Villa                   33
Juventus                      33
                              ..
Finland                        1
Austria                        1
US Orléans Loiret Football     1
Turkey                         1
Śląsk Wrocław                  1
Name: count, Length: 698, dtype: int64

In [39]:
df[df['club']=="Manchester United"]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
De Gea,David De Gea Quintana,28,1990-11-07,192,82,Spain,Manchester United
P. Pogba,Paul Pogba,26,1993-03-15,191,84,France,Manchester United
A. Martial,Anthony Martial,23,1995-12-05,184,76,France,Manchester United
M. Rashford,Marcus Rashford,21,1997-10-31,186,70,England,Manchester United
H. Maguire,Harry Maguire,26,1993-03-05,194,100,England,Manchester United
Juan Mata,Juan Manuel Mata García,31,1988-04-28,170,63,Spain,Manchester United
A. Sánchez,Alexis Alejandro Sánchez Sánchez,30,1988-12-19,169,62,Chile,Manchester United
J. Lingard,Jesse Lingard,26,1992-12-15,175,62,England,Manchester United
V. Lindelöf,Victor Nilsson Lindelöf,24,1994-07-17,187,80,Sweden,Manchester United
L. Shaw,Luke Shaw,23,1995-07-12,181,75,England,Manchester United
N. Matić,Nemanja Matić,30,1988-08-01,194,85,Serbia,Manchester United
E. Bailly,Eric Bailly,25,1994-04-12,186,77,Ivory Coast,Manchester United
S. Romero,Sergio Germán Romero,32,1987-02-22,192,86,Argentina,Manchester United
C. Smalling,Chris Smalling,29,1989-11-22,194,81,England,Manchester United
A. Wan-Bissaka,Aaron Wan-Bissaka,21,1997-11-26,183,72,England,Manchester United
Fred,Frederico R. de Paula Santos,26,1993-03-05,169,64,Brazil,Manchester United
P. Jones,Phil Jones,27,1992-02-21,185,71,England,Manchester United
M. Rojo,Faustino Marcos Alberto Rojo,29,1990-03-20,187,85,Argentina,Manchester United
S. McTominay,Scott McTominay,22,1996-12-08,193,88,Scotland,Manchester United
Andreas Pereira,Andreas Hugo Hoelgebaum Pereira,23,1996-01-01,178,71,Brazil,Manchester United
A. Young,Ashley Young,33,1985-07-09,175,65,England,Manchester United
Diogo Dalot,José Diogo Dalot Teixeira,20,1999-03-18,183,76,Portugal,Manchester United
M. Darmian,Matteo Darmian,29,1989-12-02,182,70,Italy,Manchester United
A. Tuanzebe,Axel Tuanzebe,21,1997-11-14,185,72,England,Manchester United
T. Fosu-Mensah,Timothy Evans Fosu-Mensah,21,1998-01-02,185,78,Netherlands,Manchester United
D. James,Daniel James,21,1997-11-10,170,76,Wales,Manchester United
L. Grant,Lee Grant,36,1983-01-27,193,83,England,Manchester United
A. Gomes,Angel Gomes,18,2000-08-31,169,61,England,Manchester United
M. Greenwood,Mason Greenwood,17,2001-10-01,187,65,England,Manchester United
C. Borthwick-Jackson,Cameron Borthwick-Jackson,22,1997-02-02,189,73,England,Manchester United
D. Mitchell,Demetri Mitchell,22,1997-01-11,181,71,England,Manchester United
T. Chong,Tahith Chong,19,1999-12-04,185,75,Netherlands,Manchester United
J. Garner,James Garner,18,2001-03-13,183,75,England,Manchester United

In [43]:
#display oldest players from academy
df.loc[(df['club']=="Manchester United") & (df['age']>27), 'age':'club']

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
De Gea,28,1990-11-07,192,82,Spain,Manchester United
Juan Mata,31,1988-04-28,170,63,Spain,Manchester United
A. Sánchez,30,1988-12-19,169,62,Chile,Manchester United
N. Matić,30,1988-08-01,194,85,Serbia,Manchester United
S. Romero,32,1987-02-22,192,86,Argentina,Manchester United
C. Smalling,29,1989-11-22,194,81,England,Manchester United
M. Rojo,29,1990-03-20,187,85,Argentina,Manchester United
A. Young,33,1985-07-09,175,65,England,Manchester United
M. Darmian,29,1989-12-02,182,70,Italy,Manchester United
L. Grant,36,1983-01-27,193,83,England,Manchester United

In [44]:
#get our youngest players
df.loc[(df['club']=="Manchester United") & (df['age']<28), 'age':'club']

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
P. Pogba,26,1993-03-15,191,84,France,Manchester United
A. Martial,23,1995-12-05,184,76,France,Manchester United
M. Rashford,21,1997-10-31,186,70,England,Manchester United
H. Maguire,26,1993-03-05,194,100,England,Manchester United
J. Lingard,26,1992-12-15,175,62,England,Manchester United
V. Lindelöf,24,1994-07-17,187,80,Sweden,Manchester United
L. Shaw,23,1995-07-12,181,75,England,Manchester United
E. Bailly,25,1994-04-12,186,77,Ivory Coast,Manchester United
A. Wan-Bissaka,21,1997-11-26,183,72,England,Manchester United
Fred,26,1993-03-05,169,64,Brazil,Manchester United
P. Jones,27,1992-02-21,185,71,England,Manchester United
S. McTominay,22,1996-12-08,193,88,Scotland,Manchester United
Andreas Pereira,23,1996-01-01,178,71,Brazil,Manchester United
Diogo Dalot,20,1999-03-18,183,76,Portugal,Manchester United
A. Tuanzebe,21,1997-11-14,185,72,England,Manchester United
T. Fosu-Mensah,21,1998-01-02,185,78,Netherlands,Manchester United
D. James,21,1997-11-10,170,76,Wales,Manchester United
A. Gomes,18,2000-08-31,169,61,England,Manchester United
M. Greenwood,17,2001-10-01,187,65,England,Manchester United
C. Borthwick-Jackson,22,1997-02-02,189,73,England,Manchester United
D. Mitchell,22,1997-01-11,181,71,England,Manchester United
T. Chong,19,1999-12-04,185,75,Netherlands,Manchester United
J. Garner,18,2001-03-13,183,75,England,Manchester United

In [46]:
#get youngest players and who are from england
df.loc[(df['club']=="Manchester United") & (df['age']<28) & (df['nationality']=="England"), 'age':'club']

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
M. Rashford,21,1997-10-31,186,70,England,Manchester United
H. Maguire,26,1993-03-05,194,100,England,Manchester United
J. Lingard,26,1992-12-15,175,62,England,Manchester United
L. Shaw,23,1995-07-12,181,75,England,Manchester United
A. Wan-Bissaka,21,1997-11-26,183,72,England,Manchester United
P. Jones,27,1992-02-21,185,71,England,Manchester United
A. Tuanzebe,21,1997-11-14,185,72,England,Manchester United
A. Gomes,18,2000-08-31,169,61,England,Manchester United
M. Greenwood,17,2001-10-01,187,65,England,Manchester United
C. Borthwick-Jackson,22,1997-02-02,189,73,England,Manchester United
D. Mitchell,22,1997-01-11,181,71,England,Manchester United
J. Garner,18,2001-03-13,183,75,England,Manchester United

In [49]:
#lastly tallest manunited players
df.loc[(df['club']=="Manchester United") & (df['height_cm']>185), 'age':'club']

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
De Gea,28,1990-11-07,192,82,Spain,Manchester United
P. Pogba,26,1993-03-15,191,84,France,Manchester United
M. Rashford,21,1997-10-31,186,70,England,Manchester United
H. Maguire,26,1993-03-05,194,100,England,Manchester United
V. Lindelöf,24,1994-07-17,187,80,Sweden,Manchester United
N. Matić,30,1988-08-01,194,85,Serbia,Manchester United
E. Bailly,25,1994-04-12,186,77,Ivory Coast,Manchester United
S. Romero,32,1987-02-22,192,86,Argentina,Manchester United
C. Smalling,29,1989-11-22,194,81,England,Manchester United
M. Rojo,29,1990-03-20,187,85,Argentina,Manchester United
S. McTominay,22,1996-12-08,193,88,Scotland,Manchester United
L. Grant,36,1983-01-27,193,83,England,Manchester United
M. Greenwood,17,2001-10-01,187,65,England,Manchester United
C. Borthwick-Jackson,22,1997-02-02,189,73,England,Manchester United