In [1]:
import pandas as pd

In [2]:
#read the csv file
df=pd.read_csv("sample_data/players_20.csv")

#set short_name to the index of our dataframe
df=df.set_index("short_name")

#select columns
df=df[["long_name", "age", "dob", "height_cm", "weight_kg", "nationality", "club"]]

In [3]:
#show dataframe loaded
df.head(10)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
L. Modrić,Luka Modrić,33,1985-09-09,172,66,Croatia,Real Madrid
M. Salah,Mohamed Salah Ghaly,27,1992-06-15,175,71,Egypt,Liverpool

**1. Set Value to one cell**

In [4]:
#update L.Messi Height
df.loc['L. Messi', 'height_cm']  #this displays the current height

np.int64(170)

In [5]:
df.loc['L. Messi', 'height_cm']=175   #use the assignment operator to update the height

In [6]:
#show the dataframe
df.head(1)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona

**2 Set value to entire column**

In [9]:
#set height of all players to 190   ":" this selects all the columns
df.loc[:, 'height_cm']=190

In [10]:
df.head(7)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,190,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,190,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,190,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,190,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,190,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,190,85,Germany,FC Barcelona

**3 Set Value to entire row**

In [13]:
#get all columns that correspong to player ranked last in fifa
#":"  this selects all rows,   -1 represents last number in our list
df.iloc[-1, :]

long_name                         潘喜明
age                                26
dob                        1993-01-11
height_cm                         190
weight_kg                          78
nationality                  China PR
club           Hebei China Fortune FC
Name: Pan Ximing, dtype: object

In [14]:
#set null values to all columns that corresponds to player ranked last
import numpy as np
np.nan      #this introduces null values

nan

In [16]:
#lets update our data for the last player
df.iloc[-1, :]=np.nan     #we update the last player in ranking to have all there data(rows) set to null

In [20]:
#show data
df.iloc[-1, :]

long_name      NaN
age            NaN
dob            NaN
height_cm      NaN
weight_kg      NaN
nationality    NaN
club           NaN
Name: Pan Ximing, dtype: object

**4 Set value to Multiple Cells**

In [23]:
#set value for all items matching the list of labels

df.loc[['L. Messi', 'Cristiano Ronaldo'], ['height_cm']]=175

In [24]:
#show dataframe
df.loc[['L. Messi', 'Cristiano Ronaldo']]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,175.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,175.0,83.0,Portugal,Juventus

**5 Set value for rows matching a condition**

In [26]:
#set value for rows matching a condition
columns=['age', 'dob','height_cm','weight_kg']


df.loc[df['height_cm']>180, columns]=0  #we set all rows to 0 for players above 180

In [27]:
#show dataframe
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,175.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,175.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,0.0,0,0.0,0.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,0.0,0,0.0,0.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,0.0,0,0.0,0.0,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,0.0,0,0.0,0.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,0.0,0,0.0,0.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,0.0,0,0.0,0.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,0.0,0,0.0,0.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN