In [1]:
import pandas as pd

In [5]:
#reading csv file
df_cars=pd.read_csv("sample_data/Car_sales.csv")

In [7]:
#show
df_cars

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [9]:
#select the columns we want
df_cars = df_cars[['Manufacturer', 'Sales_in_thousands',
                   'Vehicle_type', 'Price_in_thousands',
                   'Engine_size', 'Horsepower', 'Fuel_capacity']]

In [10]:
#show dataframe
df_cars

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.50,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.00,3.5,210.0,18.0
4,Audi,20.397,Passenger,23.99,1.8,150.0,16.4
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.40,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.50,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.80,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.50,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.00,2.9,201.0,21.1

In [11]:
#instead of using value_counts we see all unique value using "nunique()"
df_cars.nunique()

Manufacturer           30
Sales_in_thousands    157
Vehicle_type            2
Price_in_thousands    152
Engine_size            31
Horsepower             66
Fuel_capacity          55
dtype: int64

**1 agg()**

In [12]:
#calculate the sum of columns
df_cars.agg('sum')

Manufacturer          AcuraAcuraAcuraAcuraAudiAudiAudiBMWBMWBMWBuick...
Sales_in_thousands                                             8320.698
Vehicle_type          PassengerPassengerPassengerPassengerPassengerP...
Price_in_thousands                                             4245.567
Engine_size                                                       477.5
Horsepower                                                      29008.0
Fuel_capacity                                                    2800.5
dtype: object

In [17]:
#calculate the mean of numeric colums
#---N/B select only columns that have numerical data
df_cars.select_dtypes(include='number').agg('mean')

Sales_in_thousands     52.998076
Price_in_thousands     27.390755
Engine_size             3.060897
Horsepower            185.948718
Fuel_capacity          17.951923
dtype: float64

In [16]:
#calculate the mean and count
#N/B-- Select only columns that have integers
df_cars.select_dtypes(include='number').agg(['mean', 'count'])

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
mean,52.998076,27.390755,3.060897,185.948718,17.951923
count,157.000000,155.000000,156.000000,156.000000,156.000000

In [19]:
#Two: Mean of 'sales_in_thousands' and sum and max of 'Price_in_thousands'
df_cars.agg({'Sales_in_thousands':['sum','mean'],
             'Price_in_thousands':['sum', 'max']})

      Sales_in_thousands  Price_in_thousands
sum          8320.698000            4245.567
mean           52.998076                 NaN
max                  NaN              85.500

In [20]:
#aggregate over the columns
df_cars[['Sales_in_thousands', 'Price_in_thousands']].agg('sum', axis=1)

0      38.419
1      67.784
2      14.114
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [21]:
#equivalent(NaN behaves differently)
df_cars['Sales_in_thousands']+df_cars['Price_in_thousands']

0      38.419
1      67.784
2         NaN
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [22]:
#aggregate different functions and rename the index of the resulting dataframe
df_cars.agg(x=('Sales_in_thousands', 'sum'),
            y=('Price_in_thousands', 'sum'))

   Sales_in_thousands  Price_in_thousands
x            8320.698                 NaN
y                 NaN            4245.567

**2 The Split-Apply-Combine Strategy**

In [23]:
#lets see the data categories inthe columns
df_cars['Vehicle_type'].value_counts()

Vehicle_type
Passenger    116
Car           41
Name: count, dtype: int64

In [24]:
#split data into separate groups
passenger_filter=df_cars['Vehicle_type']=='Passenger'
car_filter=df_cars['Vehicle_type']=='Car'

In [28]:
#apply an operation
passenger_average= df_cars[passenger_filter]['Sales_in_thousands'].agg('mean')
car_average= df_cars[car_filter]['Sales_in_thousands'].agg('mean')

In [35]:
#combine the results
pd.DataFrame({'Vehicle_type':['Car', 'Passenger'],
              'Sales_in_thousands': [car_average,passenger_average]}).set_index('Vehicle_type')

              Sales_in_thousands
Vehicle_type
Car                    80.622293
Passenger              43.234345

**3 groupby()**

Group data by category

In [34]:
#group by vehicle_type and calculate the mean
#N/B we compute the mean using int columns only
df_cars.groupby('Vehicle_type').mean(numeric_only=True)

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,
Car,80.622293,26.319975,3.520000,186.400000,21.895000
Passenger,43.234345,27.763200,2.902586,185.793103,16.592241

In [38]:
#group by manufacturer
groupby_obj=df_cars.groupby('Manufacturer')

In [39]:
#the obj
groupby_obj

In [42]:
#groups attribute and keys
groupby_obj.groups.keys()

dict_keys(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet', 'Chrysler', 'Dodge', 'Ford', 'Honda', 'Hyundai', 'Infiniti', 'Jaguar', 'Jeep', 'Lexus', 'Lincoln', 'Mercedes-B', 'Mercury', 'Mitsubishi', 'Nissan', 'Oldsmobile', 'Plymouth', 'Pontiac', 'Porsche', 'Saab', 'Saturn', 'Subaru', 'Toyota', 'Volkswagen', 'Volvo'])

In [43]:
groupby_obj.get_group('Ford')

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
46,Ford,70.227,Passenger,12.070,2.0,110.0,12.7
47,Ford,113.369,Passenger,21.560,3.8,190.0,15.7
48,Ford,35.068,Passenger,17.035,2.5,170.0,15.0
49,Ford,245.815,Passenger,17.885,3.0,155.0,16.0
50,Ford,175.670,Passenger,12.315,2.0,107.0,13.2
51,Ford,63.403,Passenger,22.195,4.6,200.0,19.0
52,Ford,276.747,Car,31.930,4.0,210.0,21.0
53,Ford,155.787,Car,21.410,3.0,150.0,26.0
54,Ford,125.338,Car,36.135,4.6,240.0,26.0
55,Ford,220.650,Car,12.050,2.5,119.0,20.0
56,Ford,540.561,Car,26.935,4.6,220.0,25.1

In [46]:
#group by Manufacturer and calculate the mean
df_cars.groupby('Manufacturer').mean(numeric_only=True)

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Acura,19.751250,30.633333,2.925000,200.000000,16.400000
Audi,13.519000,39.980000,2.933333,220.000000,19.533333
BMW,15.501667,33.096667,2.700000,185.333333,17.233333
Buick,60.504750,26.781250,3.625000,206.250000,17.750000
Cadillac,22.435600,40.254000,4.500000,256.000000,20.800000
Chevrolet,61.596111,20.022778,3.055556,171.111111,15.477778
Chrysler,28.817286,23.430833,2.783333,194.833333,16.483333
Dodge,82.740818,24.213636,3.709091,199.545455,21.581818
Ford,183.875909,21.047273,3.327273,170.090909,19.063636
Honda,118.534800,20.277000,2.520000,160.400000,17.080000
Hyundai,45.775333,12.165667,1.966667,126.666667,14.533333
Infiniti,23.713000,29.465000,3.000000,227.000000,18.500000
Jaguar,15.467000,42.800000,3.000000,240.000000,18.400000
Jeep,97.717667,20.991667,3.500000,168.333333,19.833333
Lexus,17.807167,44.055000,3.616667,245.833333,20.533333
Lincoln,28.544667,41.690000,4.866667,263.333333,23.000000
Mercedes-B,13.013889,52.916667,3.422222,232.222222,18.922222
Mercury,39.666500,20.748333,3.150000,163.833333,17.833333
Mitsubishi,25.842143,22.167429,2.800000,165.142857,18.285714
Nissan,57.090714,22.360714,2.914286,169.000000,18.200000
Oldsmobile,29.831500,25.622833,3.450000,190.000000,18.200000
Plymouth,16.000250,22.642500,2.475000,166.750000,15.125000
Pontiac,61.755667,22.949167,3.433333,185.000000,17.916667
Porsche,4.042667,62.473333,3.166667,272.333333,17.000000
Saab,10.653000,29.610000,2.150000,177.500000,17.700000
Saturn,33.770000,14.271000,2.020000,119.600000,12.500000
Subaru,40.067500,21.395000,2.500000,165.000000,16.400000
Toyota,82.245000,21.982889,2.622222,160.666667,17.766667
Volkswagen,34.868667,17.698333,1.966667,120.833333,14.700000
Volvo,12.623333,30.933333,2.300000,182.166667,17.833333

In [47]:
#group by Manufacturer and then calculate the sum
df_cars.groupby('Manufacturer').sum(numeric_only=True)

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Acura,79.005,91.900,11.7,800.0,65.6
Audi,40.557,119.940,8.8,660.0,58.6
BMW,46.505,99.290,8.1,556.0,51.7
Buick,242.019,107.125,14.5,825.0,71.0
Cadillac,112.178,201.270,22.5,1280.0,104.0
Chevrolet,554.365,180.205,27.5,1540.0,139.3
Chrysler,201.721,140.585,16.7,1169.0,98.9
Dodge,910.149,266.350,40.8,2195.0,237.4
Ford,2022.635,231.520,36.6,1871.0,209.7
Honda,592.674,101.385,12.6,802.0,85.4
Hyundai,137.326,36.497,5.9,380.0,43.6
Infiniti,23.713,29.465,3.0,227.0,18.5
Jaguar,15.467,42.800,3.0,240.0,18.4
Jeep,293.153,62.975,10.5,505.0,59.5
Lexus,106.843,264.330,21.7,1475.0,123.2
Lincoln,85.634,125.070,14.6,790.0,69.0
Mercedes-B,117.125,476.250,30.8,2090.0,170.3
Mercury,237.999,124.490,18.9,983.0,107.0
Mitsubishi,180.895,155.172,19.6,1156.0,128.0
Nissan,399.635,156.525,20.4,1183.0,127.4
Oldsmobile,178.989,153.737,20.7,1140.0,109.2
Plymouth,64.001,90.570,9.9,667.0,60.5
Pontiac,370.534,137.695,20.6,1110.0,107.5
Porsche,12.128,187.420,9.5,817.0,51.0
Saab,21.306,59.220,4.3,355.0,35.4
Saturn,168.850,71.355,10.1,598.0,62.5
Subaru,80.135,42.790,5.0,330.0,32.8
Toyota,740.205,197.846,23.6,1446.0,159.9
Volkswagen,209.212,106.190,11.8,725.0,88.2
Volvo,75.740,185.600,13.8,1093.0,107.0

In [48]:
df_cars.value_counts('Manufacturer')

Manufacturer
Ford          11
Dodge         11
Chevrolet      9
Mercedes-B     9
Toyota         9
Chrysler       7
Mitsubishi     7
Nissan         7
Mercury        6
Oldsmobile     6
Lexus          6
Pontiac        6
Volvo          6
Volkswagen     6
Cadillac       5
Honda          5
Saturn         5
Plymouth       4
Buick          4
Acura          4
Audi           3
BMW            3
Lincoln        3
Porsche        3
Jeep           3
Hyundai        3
Saab           2
Subaru         2
Jaguar         1
Infiniti       1
Name: count, dtype: int64

In [49]:
#group by vehicle_type and count values
df_cars.groupby('Vehicle_type').count()

,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,,
Car,41,41,40,40,40,40
Passenger,116,116,115,116,116,116

In [50]:
#find null values in columns
df_cars.isnull().sum()

Manufacturer          0
Sales_in_thousands    0
Vehicle_type          0
Price_in_thousands    2
Engine_size           1
Horsepower            1
Fuel_capacity         1
dtype: int64

In [51]:
#group by Engine_size and count values without dropping NaN values
df_cars.groupby('Engine_size', dropna=False).count()

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Horsepower,Fuel_capacity
Engine_size,,,,,,
1.0,1,1,1,1,1,1
1.5,1,1,1,1,1,1
1.6,1,1,1,1,1,1
1.8,8,8,8,8,8,8
1.9,5,5,5,5,5,5
2.0,17,17,17,17,17,17
2.2,4,4,4,4,4,4
2.3,6,6,6,6,6,6
2.4,11,11,11,11,11,11
2.5,11,11,11,11,11,11
2.7,4,4,4,4,4,4
2.8,3,3,3,3,3,3
2.9,1,1,1,1,1,1
3.0,14,14,14,14,14,14
3.1,4,4,4,4,4,4
3.2,6,6,6,5,6,6
3.3,5,5,5,5,5,5
3.4,7,7,7,7,7,7
3.5,8,8,8,8,8,8
3.8,8,8,8,8,8,8
3.9,2,2,2,2,2,2
4.0,7,7,7,7,7,7
4.2,1,1,1,1,1,1
4.3,2,2,2,2,2,2
4.6,9,9,9,9,9,9
4.7,2,2,2,2,2,2
5.0,2,2,2,2,2,2
5.2,2,2,2,2,2,2
5.4,1,1,1,1,1,1
5.7,2,2,2,2,2,2
8.0,1,1,1,1,1,1
NaN,1,1,1,0,0,0

**4 Groupby() and agg()**

In [52]:
#find the minimum and maximum values on each column
df_cars.groupby('Vehicle_type').min()

,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,,
Car,Cadillac,9.126,11.528,2.0,119.0,15.1
Passenger,Acura,0.110,9.235,1.0,55.0,10.3

In [53]:
#maximum value of each column
df_cars.groupby('Vehicle_type').max()

,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,,
Car,Toyota,540.561,60.105,5.7,300.0,32.0
Passenger,Volvo,247.994,85.500,8.0,450.0,23.7

In [54]:
#get them at the same time
df_cars.groupby('Vehicle_type').agg(['min', 'max'])

             Manufacturer         Sales_in_thousands           \
                      min     max                min      max
Vehicle_type
Car              Cadillac  Toyota              9.126  540.561
Passenger           Acura   Volvo              0.110  247.994

             Price_in_thousands         Engine_size      Horsepower         \
                            min     max         min  max        min    max
Vehicle_type
Car                      11.528  60.105         2.0  5.7      119.0  300.0
Passenger                 9.235  85.500         1.0  8.0       55.0  450.0

             Fuel_capacity
                       min   max
Vehicle_type
Car                   15.1  32.0
Passenger             10.3  23.7

In [55]:
#Find the min Engine_size and max Horsepower
df_cars.groupby('Vehicle_type').agg(min_engine_size=('Engine_size', 'min'),
                                    max_horsepower=('Horsepower', 'max'))

              min_engine_size  max_horsepower
Vehicle_type
Car                       2.0           300.0
Passenger                 1.0           450.0

In [56]:
#calculate the sum of sales_in_thousands and mean of Price_in_thousands
df_cars.groupby('Manufacturer').agg(sum_sales=('Sales_in_thousands', 'sum'),
                                    mean_price=('Price_in_thousands', 'mean'))

              sum_sales  mean_price
Manufacturer
Acura            79.005   30.633333
Audi             40.557   39.980000
BMW              46.505   33.096667
Buick           242.019   26.781250
Cadillac        112.178   40.254000
Chevrolet       554.365   20.022778
Chrysler        201.721   23.430833
Dodge           910.149   24.213636
Ford           2022.635   21.047273
Honda           592.674   20.277000
Hyundai         137.326   12.165667
Infiniti         23.713   29.465000
Jaguar           15.467   42.800000
Jeep            293.153   20.991667
Lexus           106.843   44.055000
Lincoln          85.634   41.690000
Mercedes-B      117.125   52.916667
Mercury         237.999   20.748333
Mitsubishi      180.895   22.167429
Nissan          399.635   22.360714
Oldsmobile      178.989   25.622833
Plymouth         64.001   22.642500
Pontiac         370.534   22.949167
Porsche          12.128   62.473333
Saab             21.306   29.610000
Saturn          168.850   14.271000
Subaru           80.135   21.395000
Toyota          740.205   21.982889
Volkswagen      209.212   17.698333
Volvo            75.740   30.933333

In [57]:
#under the hood
df_cars.groupby('Manufacturer').sum()['Sales_in_thousands']

Manufacturer
Acura           79.005
Audi            40.557
BMW             46.505
Buick          242.019
Cadillac       112.178
Chevrolet      554.365
Chrysler       201.721
Dodge          910.149
Ford          2022.635
Honda          592.674
Hyundai        137.326
Infiniti        23.713
Jaguar          15.467
Jeep           293.153
Lexus          106.843
Lincoln         85.634
Mercedes-B     117.125
Mercury        237.999
Mitsubishi     180.895
Nissan         399.635
Oldsmobile     178.989
Plymouth        64.001
Pontiac        370.534
Porsche         12.128
Saab            21.306
Saturn         168.850
Subaru          80.135
Toyota         740.205
Volkswagen     209.212
Volvo           75.740
Name: Sales_in_thousands, dtype: float64

In [60]:
df_cars.groupby('Manufacturer').mean(numeric_only=True)['Price_in_thousands']

Manufacturer
Acura         30.633333
Audi          39.980000
BMW           33.096667
Buick         26.781250
Cadillac      40.254000
Chevrolet     20.022778
Chrysler      23.430833
Dodge         24.213636
Ford          21.047273
Honda         20.277000
Hyundai       12.165667
Infiniti      29.465000
Jaguar        42.800000
Jeep          20.991667
Lexus         44.055000
Lincoln       41.690000
Mercedes-B    52.916667
Mercury       20.748333
Mitsubishi    22.167429
Nissan        22.360714
Oldsmobile    25.622833
Plymouth      22.642500
Pontiac       22.949167
Porsche       62.473333
Saab          29.610000
Saturn        14.271000
Subaru        21.395000
Toyota        21.982889
Volkswagen    17.698333
Volvo         30.933333
Name: Price_in_thousands, dtype: float64